# Generated by Django 2.2.5 on 2019-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=2)),
                ('number', models.CharField(blank=True, max_length=3)),
                ('mass', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(choices=[('s', 'Solid'), ('g', 'Gas'), ('l', 'Liquid'), ('u', 'Unknown'), ('f', 'Fictional')], max_length=1)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
